```{r}
# install.packages("jsonlite")
library(jsonlite) # used to read large JSON files

# install.packages("rjson")
# library(rjson)

# install.packages("split")
# library(split) # used to split large JSON files in R

library(dplyr)

library(tidyverse)

```

### File size
```{r}
file.info("/Users/jiatonghan/Downloads/Manifold Data/bets.json")$size
# 6766040782 bytes

file.info("/Users/jiatonghan/Downloads/Manifold Data/manifold-contracts-20240706.json")$size
# 463420663 bytes

file.info("/Users/jiatonghan/Downloads/Manifold Data/manifold-comments-20240706hi.json")$size
# 609518639 bytes
```

### Bet data
```{r}
data.bets <- jsonlite::read_json("/Users/jiatonghan/Downloads/Manifold Data/bets.json") # take hours to run, 37.6GB
# list of 9115727 elements

data.bets.top10k <- data.bets[1:10000]
# save(data.bets.top10k, file = "data.bets.top10k.RData")
# load("~/Downloads/Manifold Data/data.bets.top10k.RData")
str(data.bets.top10k[1:10])


# convert the list to a data frame
df.bets.top10k <- bind_rows(data.bets.top10k)
print(df.bets.top10k)

```

### Contracts data
```{r}
# Load the data
data.contracts <- jsonlite::read_json("/Users/jiatonghan/Downloads/Manifold Data/manifold-contracts-20240706.json")
# list of 130091 

data.contracts.top10k <- data.contracts[1:10000]

# save(data.contracts.top10k, file = "data.contracts.top10k.RData")
# load("~/Downloads/Manifold Data/data.contracts.top10k.RData")

str(data.contracts.top10k[1:5])

# convert the list to a data frame
df.contracts.top10k <- map_dfr(data.contracts.top10k, function(x) {
  x$description <- NULL  # delete the description column, otherwise the data frame will be too wide
  x$groupLinks <- NULL # # delete the groupLinks column, otherwise the data frame will be too wide
  x$answers <- NULL # # delete the answers column, otherwise the data frame will be too wide
  x$resolutions <- NULL # # delete the resolutions column, otherwise the data frame will be too wide
  as.data.frame(t(unlist(x)))
})
str(df.contracts.top10k)
```

### Comment data
```{r}
# Load the data
data.comments <- jsonlite::read_json("/Users/jiatonghan/Downloads/Manifold Data/manifold-comments-20240706hi.json")
# list of 528693

data.comments.top10k <- data.comments[1:10000]
# save(data.comments.top10k, file = "data.comments.top10k.RData")
# load("~/Downloads/Manifold Data/data.comments.top10k.RData")

# convert the list to a data frame
df.comments.top10k <- map_dfr(data.comments.top10k, function(x) {
  as.data.frame(t(unlist(x)))
})

str(df.comments.top10k[1:5])

```
